package:
  name: micro_ges
  version: 1.0.0

source:
  path: ..

build:
  number: 0
  rpaths:
    - lib/R/lib

requirements:
  build:
    - r-base
  run:
    - r-base

about:
  home: https://github.com/bioinformatics-ua/MicroGES
  license: GPL-3.0
  license_file: LICENSE
  summary: R solution to identify gene expression signatures in microarray datasets
  doc_url: https://github.com/bioinformatics-ua/MicroGES/wiki
